### ISSUE TITLE
Buttons are switched

### ISSUE THREAD

**Issue by rogerjak** [mikitex70/redmine_drawio#5]
Great plugin!
The new toolbar buttons are wrong though; the dmsf one generates drawio_attach and the opposite for the other one.
Also, the new embedded editor doesn't work for me, I think it's because we don't run redmine at root url, because of Bitnami.
Thanks
Roger

**Comment by mikitex70** [comment]
Fixed.
Thanks for reporting the issue.

**Comment by rogerjak** [comment]
Thanks, the buttons are ok now.
But attach and edit still doesn't work. The placeholder is just a "missing image" and when I click save in the editor it tries to connect to the root so I get prompted for credentials and it all fails.

**Comment by mikitex70** [comment]
I will look for your problem tonight, maybe there are other places where I need to inject the Redmine path.
Sorry, I've not deeply tested the code...

**Comment by mikitex70** [comment]
I've tried Redmine in Bitnami and works fine for me. If you are using the DMSF plugin, make sure to enable its WebDAV capability in Read/Write mode to avoid an HTTP 502 error.
Are you using Bitnami on Linux or Windows? If you are using the Windows version maybe the plugin has a problem in the path management. I will do a Windows test tomorrow.
Try also to do a clean checkout of the plugin, and use the master branch as now is released. Maybe it can help.

**Comment by rogerjak** [comment]
After I click save in the editor and enter the credentials, the wiki page is updated with a new attachment. So far so good, but there's no diagram visible on the page, only the "missing image" thing.

Also, the page gets messed up, I have a plugin that automatically adds headers/footers to all wiki pages, and that "external text" is added to my page somehow.

**Comment by mikitex70** [comment]
Hi rogerjak, I've pushed in the develop branch a new pre-release.
This version should fix the problems running in Windows (tested with Bitnami 3.3.1-0 with Windows 7), plus some fix for Internet Explorer (tested with Internet Explorer 11).
If you have troubles with the diagram editor (such as pages messed up), try using Firefox or Chrome.
