### ISSUE TITLE
no edit mode after saving an empty page

### ISSUE THREAD

**Issue by butterflysb86** [mikitex70/redmine_drawio#71]
I use your Redmine plugin for drawio. I noticed that I get an empty start page back when I save an empty page. It is then no longer possible to start the edit mode by double-clicking. We had to go back in history and restore an older version to be able to use the plugin again. Is the problem known? We use redmine drawio plugin version 0.8.3 and Redmine version 3.4.6 on a linux server (Ubuntu 16). The browser console does not show any errors.
Environment:
  Redmine version                3.4.6.stable
  Ruby version                   2.4.4-p296 (2018-03-28) [x86_64-linux]
  Rails version                  4.2.8
  Environment                    production
  Database adapter               PostgreSQL
SCM:
  Subversion                     1.9.5
  Mercurial                      4.0
  Bazaar                         2.8.0
  Git                            2.11.0
  Filesystem                     
Redmine plugins:
  redmine_agile                  1.4.6
  redmine_checklists             3.1.11
  redmine_contacts               4.1.2
  redmine_contacts_helpdesk      3.0.9
  redmine_dmsf                   1.6.1
  redmine_drawio                 0.8.3
  redmine_mattermost             0.6
  redmine_people                 1.3.2
  redmine_private_wiki           0.2.0
  redmine_questions              1.0.0
  redmine_slack                  0.2
  redmine_xlsx_format_issue_exporter 0.1.5

**Comment by mikitex70** [comment]
I will setup a test environment in the weekend so I can do some testing and try to reproduce the issue.
In the meanwhile can you try with the version 0.9.0? Maybe it has been fixed indirectly by some commit.

**Comment by butterflysb86** [comment]
Thanks for the support. We will be able to install version 0.9.0 on our test system next week at the earliest. Then it might make more sense to check it out first. If it is not solved yet, you can still setup the test environment.

**Comment by butterflysb86** [comment]
I have tested version 0.9.0, but the problem persists. Even if we change to redmine version 4.0.5.

**Comment by mikitex70** [comment]
I'm unable to reproduce the problem, for me it works fine. My configuration is not exactly as yours (some plugins have different version), but I'm almost sure that there aren't incompatibilities.
Check the user privileges in Redmine: the user must be able to edit wiki pages and to save files in the DMS plugin or as attachment..
Also check if there is some browser plugin that blocks popups or do some other security check.

**Comment by butterflysb86** [comment]
The user privileges and the browser settings can't be the reason, because I can save changes in drawio. It only occurs when I create a new page with the drawio plugin and save it. Then I am on the Redmine site again. There I see an empty page, which is correct in that sense, but the function to open the edit mode with a double click is no longer available.  Here is an example:
![image](https://user-images.githubusercontent.com/56911660/69053338-7c066a00-0a09-11ea-8804-53fee96dba2a.png)
With a double click I switch to the edit mode. 
![image](https://user-images.githubusercontent.com/56911660/69053467-c1c33280-0a09-11ea-9715-f7d8cfa76c9b.png)
If I now create a new empty page, rename it and save it, I have the following result:
![image](https://user-images.githubusercontent.com/56911660/69053455-b96af780-0a09-11ea-9b47-d992d33d1596.png)
Here is no double-click option:
![image](https://user-images.githubusercontent.com/56911660/69053298-6729d680-0a09-11ea-80ff-0d0a4d4ccce9.png)

**Comment by mikitex70** [comment]
Ok, now I've understood the issue and I'm able to reproduce it.
I'm not sure to be able to fix it,I must detect an empty diagram which does not means an empty file.
But, why save an empty diagram? I understand that is something that can happen, but to delete a diagram is much more simple and secure to remove the macro from the wiki page.
Give me some day, I will try to fix this iissue.

**Comment by butterflysb86** [comment]
Thank you! We save empty renamed pages before linking them to other pages.

**Comment by mikitex70** [comment]
I've made a fix in the develop branch.
Can you give it a try to see if it is a reasonable solution?
When you confirm that it is working fine I will made an official release.

**Comment by butterflysb86** [comment]
Thank you! I tested the new version. Unfortunately it's not as I need it yet.  If I save an empty 2nd page, but there is still a 1st page with content, double click should open the edit mode and I should see page 1 (with content) again. For example:
I start with:
![image](https://user-images.githubusercontent.com/56911660/69539304-7fa76d00-0f84-11ea-9421-014a98839aa4.png)
and double click:
![image](https://user-images.githubusercontent.com/56911660/69539346-92ba3d00-0f84-11ea-8cd8-aacff76cef44.png)
Now I save the empty page with name "test_page"
![image](https://user-images.githubusercontent.com/56911660/69539404-afef0b80-0f84-11ea-8183-7d852b656022.png)
And I get this:
![image](https://user-images.githubusercontent.com/56911660/69539423-ba110a00-0f84-11ea-89f7-0f758ac70cc2.png)
Up to here it is correct. But if I now switch to edit mode with a double click, the content of page 1 is gone.
![image](https://user-images.githubusercontent.com/56911660/69539501-e9c01200-0f84-11ea-8ee4-f5f8f236a33d.png)
But I would expect this result:
![image](https://user-images.githubusercontent.com/56911660/69539581-14aa6600-0f85-11ea-8407-7d8d5a4a0961.png)

**Comment by mikitex70** [comment]
Ok, I understand a bit more, but I have some question for you:
1. what macro are you using, `drawio_dmsf` or `drawio_attach`? They use a completely different storage method (the dmsf is versioned, the attach is versioned changing attachment name)
2. if I've understood correctly what you want is: when saving an empty diagram, the save doesn't happen and the old diagram is left untouched. Is that correct? If so, this is easy to implement.
3. or the problem arises when you create a multi-page diagram? I never tested multi-page diagrams, but what is done is an "export" of the diagram to png o svg format. During export drawio renders the image of the active page, so maybe it is better to switch to the first page (which have the diagram) before saving it. I'm not sure that there is an API in the drawio editor to force a page change, so I'm not sure to be able to fix this issue.

**Comment by butterflysb86** [comment]
1. we use drawio_dmsf
2. no, we want that the save does happen, but we only want that it is like caching and you can go on after save. 
3. yes we use multi-page diagram. We want to use it with other users and we can tell them, that they have to switch to the first page before saving, but I think someone will forget it and then all is gone.  That happened twice. 
Yes, you could force a switch. But maybe you could also display both pages (the full 1st page and the empty 2nd page) after saving the empty 2nd page, if you switch back to edit mode. Isn't that possible?

**Comment by mikitex70** [comment]
I don't have control on how drawio saves the diagrams, I can only trigger the save.
Do a new pull from the develop and try this version: when a diagram is empty the save is blocked. If it is a multi-page diagram then the message says to switch to another non-empty page.

**Comment by butterflysb86** [comment]
Thank you very much. That helps me a lot!
