### ISSUE TITLE
Content Security Policy preventing plugin from working?

### ISSUE THREAD

**Issue by xanadiu** [mikitex70/redmine_drawio#85]
I am trying to get the plugin working, but with no success.

I...
- [x]  installed version 0.9.9 of the plugin
- [x] with Redmine 4.1.4,
- [x] I configured `//app.diagrams.net` as the Draw.io service URL and
- [x] made sure that the REST API is (already) active.

To test the plugin I have attached a diagram „minitest.svg“ to a wiki page and embedded it with `{{drawio_attach(minitest.svg)}}` in the page where it is displayed correctly.

But when I double-click on the diagram, nothing seems to happen except that all links on the page are disabled. After some investigation I found two errors appearing in the JavaScript console:

> [Error] Refused to load https://app.diagrams.net/images/ajax-loader.gif because it does not appear in the img-src directive of the Content Security Policy.

> [Error] Refused to load https://app.diagrams.net/?embed=1&ui=atlas&spin=1&modified=unsavedChanges&proto=json&https=1 because it appears in neither the child-src directive nor the default-src directive of the Content Security Policy.

So I wonder if this is a known error / behavior as I did not find any posts covering this situation. I did try this with Safari, Firefox and Chrome in recent versions - none of them is working.

Is there some publicly available Redmine instance with the plugin running to perform some cross-checks?

**Comment by mikitex70** [comment]
Hi @xanadiu, sorry for the delay.
I have done some test and all works fine. What is wrong is the url of the online service: the correct url is `//embed.diagrams.net`, which is the default if you leave the parameter blank in the configuration (the hint is wrong, I've fixed it in the develop branch).

**Comment by xanadiu** [comment]
Hi @mikitex70, I also tried the plugin with the default configuration by explicitly entering `//embed.diagrams.net` which results in the same console errors (with the adopted URLs).

But when I leave the configuration value blank, there is the interesting effect that the console errors turn into:
> [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (ajax-loader.gif, line 0)

So the resource `/images/ajax-loader.gif` is not found on our installation (the loading is initiated by /javascripts/jquery-2.2.4-ui-1.11.0-ujs-5.2.3.js).

After this the wiki page is reloaded.

Does this provide any hints for further debugging / investigation?

**Comment by mikitex70** [comment]
Hi @xanadiu, I've done some more test and yes, there is a bug when the configuration url is changed from the default (empty) to some string and then back to empty: in this case the default `//embed.diagrams.net` is ignored and then shows the error trying to load the `ajax-loader.gif` image.
But if the url is set to `//embed.diagrams.net` it should work fine.
You mentioned that you've attached an svg diagram, then you have tried to edit id: be sure that the svg diagram is saved with the embedded source, otherwise it cannnot be edited.
Try to create a new diagram (simply use a `drawio_attach` macro with a non-existent attachment) to test if it is working.
Another thing to test is that your browser can access internet (but I'm sure it's so).
And... what browser are you using? My tests are done with Firefox.

**Comment by mikitex70** [comment]
No more feedback, closing the issue.

**Comment by mikitex70** [comment]
The bug is now fixed in version `v1.0.0`.
No more feedback, so I close this issue.

**Comment by xanadiu** [comment]
Hi @mikitex70, sorry for not getting back to you earlier.

I just tested my installation with `v1.0.2` of the plugin, but without any luck. The behaviour remains the same.

I still get CSP-Errors in the console when I try to edit a diagram (with a double-click).

My environment:
* Redmine: `4.1.1.stable`
* Firefox: `88.0.1` (also applies to Safari and Chrome)
* redmine_drawio: `1.0.2`

I also followed your advice to create a macro for a non-existing diagram, but this does not affect the browser's behaviour.

Attached you find the SVG file in question which is attached to the wiki page (zipped as GitHub does not accept it natively): [minitest.svg.zip](https://github.com/mikitex70/redmine_drawio/files/6521540/minitest.svg.zip)

Additionally, two screenshots (before and after trying to edit the second diagram). You can find the CSP-Errors in the console.

Please let me know if you need further information.

<img width="1205" alt="Bildschirmfoto 2021-05-21 um 11 30 25" src="https://user-images.githubusercontent.com/23736160/119116409-80f61080-ba28-11eb-9f60-c394e7ecc663.png">

<img width="1205" alt="Bildschirmfoto 2021-05-21 um 11 30 32" src="https://user-images.githubusercontent.com/23736160/119116443-881d1e80-ba28-11eb-9186-b11f60a34b09.png">

**Comment by mikitex70** [comment]
Upgraded Firefox to version 88, but I cannot reproduce the issue.
Are you behind a proxy, or is Redmine installation exposed with a reverse-proxy?
Can you check then request and response headers of the blocked request? Maybe there is some hint on why they are blocked.

**Comment by xanadiu** [comment]
The blocked request does not show up in the network analyser as it is blocked. But the Redmine HTML content, which I suspect to be responsible, has these response headers:

* Content-Security-Policy: default-src 'self'; script-src 'unsafe-inline' 'self' 'unsafe-eval'; connect-src 'self'; img-src 'self'; style-src 'unsafe-inline' 'self'
* Referrer-Policy: strict-origin-when-cross-origin

Redmine is served by Apache via Passenger Phusion. Could that constellation be misconfigured?

**Comment by mikitex70** [comment]
I have set up a test environment using Traefik 2 and I can confirm that is the header `Content-Security-Policy` that create problems.
I think it is configured in Apache; try to change the value in:
```
default-src 'self' embed.diagrams.net; script-src 'unsafe-inline' 'self' 'unsafe-eval' ; connect-src 'self'; img-src 'self' data: embed.diagrams.net; style-src 'unsafe-inline' 'self'
```
In my tests this value resolves the problem allowing to use scripts ad images from the `embed.diagrams.net` site (the diagram editor).
If security is an issue, you can try to install the drawio website locally (it's a war) and configure the drawio plugin to use your local installation. The suggested header must be changed accordingly.

**Comment by xanadiu** [comment]
@mikitex70 Thanks a lot!! That configuration issue was the reason for failure. Now it works like a charm! Maybe it might be worth mentioning this requirement if others also encounter(ed) this situation?

Again, thanks for investigating with me!

**Comment by mikitex70** [comment]
It's a good idea.
I think the configuration is distribution dependent. What kind of Redmine distribution are you usiing (vaniilla, Bitnami, container, ecc.)? If installed with a package manager, what OS is?

**Comment by xanadiu** [comment]
Our Remine installation is running on a Linux VM with Ubuntu 20.04.2 LTS. AFAIK our system administrator did a vanilla deployment with hand-crafted integration into Apache with Phusion Passenger.

For me, the advice to pay attention to the security headers and mentioning the reverse-proxy configuration were the missing link.

**Comment by mikitex70** [comment]
Added a section on the `Content-Security-Policy` header configuration in the README.md.
Thanks for letting me known this new header.
